### ISSUE TITLE
warning in install.packages

### ISSUE THREAD

**Issue by li-jinyan** [YuLab-SMU/yulab.utils#2]
I want to use install_zip_gh to install "YuLab-SMU/ggtree",but it has some trouble:

> yulab.utils::install_zip_gh("YuLab-SMU/ggtree")
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  344k    0  344k    0     0   114k      0 --:--:--  0:00:03 --:--:--  110k
√  checking for file 'C:\Users\li\AppData\Local\Temp\RtmpQxIZEA\file2c4c705b521f\ggtree-master/DESCRIPTION' (384ms)
-  preparing 'ggtree':
√  checking DESCRIPTION meta-information (2.1s)
-  checking for LF line-endings in source and make files and shell scripts (392ms)
-  checking for empty or unneeded directories
-  building 'ggtree_2.3.4.993.tar.gz'
   
Warning in install.packages :
  package ‘C:/Users/li/AppData/Local/Temp/RtmpQxIZEA/file2c4c705b521f/ggtree_2.3.4.993.tar.gz’ is not available (for R version 3.6.1)
> library(ggtree)
Error in library(ggtree) : there is no package called ‘ggtree’

how could I solve this problem? Should I update my R to R-4.0?

**Comment by GuangchuangYu** [comment]
I only test the package on Linux. Don't know whether the [PR](https://github.com/YuLab-SMU/yulab.utils/pull/1) solve your problem or not.

**Comment by GuangchuangYu** [comment]
![image](https://github.com/YuLab-SMU/yulab.utils/assets/626539/5873d195-2ccc-4f32-9d77-137f4372f28d)

it works.
