### ISSUE TITLE
ı couldnot install any package with correlated yulab.utils

### ISSUE THREAD

**Issue by semraugur** [YuLab-SMU/yulab.utils#6]
`install.packages("scatterpie")
Installing package into ‘/home/semra/R/x86_64-pc-linux-gnu-library/4.1’
(as ‘lib’ is unspecified)
also installing the dependencies ‘ggfun’, ‘yulab.utils’

URL 'https://cran.gedik.edu.tr/src/contrib/ggfun_0.1.6.tar.gz' deneniyor
Content type 'application/x-gzip' length 104703 bytes (102 KB)
==================================================
downloaded 102 KB

URL 'https://cran.gedik.edu.tr/src/contrib/yulab.utils_0.1.7.tar.gz' deneniyor
Content type 'application/x-gzip' length 23777 bytes (23 KB)
==================================================
downloaded 23 KB

URL 'https://cran.gedik.edu.tr/src/contrib/scatterpie_0.2.4.tar.gz' deneniyor
Content type 'application/x-gzip' length 118771 bytes (115 KB)
==================================================
downloaded 115 KB

* installing *source* package ‘yulab.utils’ ...
** package ‘yulab.utils’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error in (function (bibtype, textVersion, header = NULL, footer = NULL,  : 
  ‘bibtype’ has to be one of Article, Book, Booklet, InBook, InCollection, InProceedings, Manual, MastersThesis, Misc, PhdThesis, Proceedings, TechReport, Unpublished
Hata: unable to load R code in package ‘yulab.utils’
Çalıştırma durduruldu
ERROR: lazy loading failed for package ‘yulab.utils’
* removing ‘/home/semra/R/x86_64-pc-linux-gnu-library/4.1/yulab.utils’
ERROR: dependency ‘yulab.utils’ is not available for package ‘ggfun’
* removing ‘/home/semra/R/x86_64-pc-linux-gnu-library/4.1/ggfun’
ERROR: dependencies ‘ggfun’, ‘yulab.utils’ are not available for package ‘scatterpie’
* removing ‘/home/semra/R/x86_64-pc-linux-gnu-library/4.1/scatterpie’

The downloaded source packages are in
	‘/tmp/RtmpjxxuxH/downloaded_packages’
Warning messages:
1: In install.packages("scatterpie") :
  installation of package ‘yulab.utils’ had non-zero exit status
2: In install.packages("scatterpie") :
  installation of package ‘ggfun’ had non-zero exit status
3: In install.packages("scatterpie") :
  installation of package ‘scatterpie’ had non-zero exit status
`

**Comment by GuangchuangYu** [comment]
This issue should be solved in current version.

**Comment by semraugur** [comment]
no ı have problem still
